version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    # used to access from local machine
    # ports:
    #   - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
    - hub
    deploy:
      replicas: 0  
    environment: 
    - SE_EVENT_BUS_HOST
    - SE_EVENT_BUS_PUBLISH_PORT
    - SE_EVENT_BUS_SUBSCRIBE_PORT
    - SE_NODE_OVERRIDE_MAX_SESSIONS
    - SE_NODE_MAX_SESSIONS
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
    - hub
    deploy:
      replicas: 0  
    environment: 
    - SE_EVENT_BUS_HOST
    - SE_EVENT_BUS_PUBLISH_PORT
    - SE_EVENT_BUS_SUBSCRIBE_PORT
    - SE_NODE_OVERRIDE_MAX_SESSIONS
    - SE_NODE_MAX_SESSIONS