version: "3"
services:
  test-suites:
    image: luckymantala/selenium:latest  
    environment:
      - HUB_HOST=hub
      - BROWSER
      - THREAD_COUNT=3
      - TEST_SUITE
    volumes:
      - C:\Users\ATUser001\git\selenium-docker-cicd\output\$TEST_SUITE:/home/selenium-docker-cicd/test-output
