version: "3"
services:
  test-suites:
    image: luckymantala/selenium:latest  
    environment:
      - HUB_HOST=hub
      - BROWSER
      - THREAD_COUNT=1
      - TEST_SUITE
    volumes:
      - .\output\$TEST_SUITE:/home/selenium-docker-cicd/test-output
